import Link from 'next/link';
import { Metadata } from "next"

export const metadata : Metadata = {
  title: {
    absolute: "Shop",
  },
  description: 'Generated by Next.js',

}


export default function Shop(){


//possible d emettr el id de page dans une variable
const productId = 77;

  return (
    <div className='w-full h-screen flex items-center justify-center'>
    <h1 className="text-center text-slate-900 text-4xl my-6">PAGE BOUTIQUE</h1>

    <ul >
        <li>
          <Link href="/shop/1">Produit 1</Link>
        </li>
        <li >
          <Link href="/shop/2">Produit 2</Link>
        </li>
        <li >
          <Link href={`/shop/${productId}`}>Produit {productId}</Link>
        </li>
        <li >
          <Link href="/shop/4" replace>Produit 4</Link>
        </li>
      {/* // Replace (facultatif): C'est un attribut qui, lorsqu'il est défini sur true, remplace l'historique de navigation au lieu de l'ajouter lors du clic sur le lien. Cela peut être utile dans certains scénarios de navigation. */}
        <li >
          <Link href="/shop/5" passHref>Produit 5</Link>
        </li>
      {/* // PassHref (facultatif):  il transmet les props spéciales nécessaires pour que le lien fonctionne correctement. Cela peut être nécessaire dans certains cas particuliers. */}
        <li >
          <Link href="/shop/6" prefetch >Produit 6</Link>
        </li>
      {/*  // Prefetch (facultatif): Cet attribut, lorsqu'il est défini sur true, permet à Next.js de prefetcher la page vers laquelle le lien pointe. Cela signifie que la page est préchargée en arrière-plan pour une navigation plus rapide lorsque le lien est survolé. */}
      </ul>
  </div>
  )
}


//Voir page layout de auth
