import './index.css'
import Navigation from "@/components/Navigation"
import Footer from "@/components/Footer"



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  absolute: "",
  default: "Next JS - Formation",
  template: "%s | La Minute De Code ",
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
        </body>
    </html>
  )
}
