
import { Metadata } from "next"

export const metadata : Metadata = {
  title: {
    absolute: "Shop",
  },
  description: 'Generated by Next.js',

}


export default function Shop(){
  return (
    <div className='w-full h-screen flex items-center justify-center'>
    <h1 className="text-center text-slate-900 text-4xl my-6">PAGE BOUTIQUE</h1>
  </div>
  )
}