import Link from 'next/link';
import { Metadata } from "next"

export const metadata : Metadata = {
  title: {
    absolute: "Shop",
  },
  description: 'Generated by Next.js',

}


export default function Shop(){



const productId = 77;

  return (
    <div className='w-full h-screen flex items-center justify-center'>
    <h1 className="text-center text-slate-900 text-4xl my-6">PAGE BOUTIQUE</h1>

    <ul >
        <li>
          <Link href="/shop/1">Produit 1</Link>
        </li>
        <li >
          <Link href="/shop/2">Produit 2</Link>
        </li>
        <li >
          <Link href={`/shop/${productId}`}>Produit {productId}</Link>
        </li>
        <li >
          <Link href="/shop/4" replace>Produit 4</Link>
        </li>
              <li >
          <Link href="/shop/5" passHref>Produit 5</Link>
        </li>
        <li >
          <Link href="/shop/6" prefetch >Produit 6</Link>
        </li>
      </ul>
  </div>
  )
}

